/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A Node.js handle to one Holt tree. */
export declare class Tree {
  /** Open a file-backed tree. */
  static open(path: string, options?: TreeOptions | undefined | null): Tree
  /** Open a volatile in-memory tree. */
  static openMemory(): Tree
  /** Explicitly release the native tree handle. This is idempotent. */
  close(): void
  /** Return the value stored at `key`, or null when the key is absent. */
  get(key: Uint8Array): Buffer | null
  /** Return the value and conditional-write version for `key`. */
  getRecord(key: Uint8Array): Record | null
  /** Insert or replace a value. */
  put(key: Uint8Array, value: Uint8Array): void
  /** Delete a key and return whether a live record existed. */
  delete(key: Uint8Array): boolean
  /** Compare the current version and replace the value if it matches. */
  compareAndPut(key: Uint8Array, version: bigint, value: Uint8Array): boolean
  /** Flush dirty frames and the WAL to the backing store. */
  checkpoint(): void
  /** Scan keys under an optional prefix. */
  scanKeys(prefix?: Uint8Array | undefined | null, options?: ScanOptions | undefined | null): Array<ScanEntry>
  /** Scan records under an optional prefix. */
  scanRecords(prefix?: Uint8Array | undefined | null, options?: ScanOptions | undefined | null): Array<ScanEntry>
}

/** A live value and its conditional-write version. */
export interface Record {
  /** Value bytes stored at the key. */
  value: Buffer
  /** Version token for compare-and-put. */
  version: bigint
}

/** One emitted scan entry. */
export interface ScanEntry {
  /** `key` for a live record or `common_prefix` for a rollup. */
  kind: string
  /** Key or common-prefix bytes. */
  path: Buffer
  /** Value bytes; absent for key-only scans and common-prefix entries. */
  value?: Buffer
  /** Conditional-write version. Zero for common-prefix entries. */
  version: bigint
}

/** Options shared by key and record scans. */
export interface ScanOptions {
  /** Exclusive lower-bound key. */
  startAfter?: Uint8Array
  /** Optional delimiter byte used for common-prefix rollups. */
  delimiter?: number
}

/** Options for opening a file-backed tree. */
export interface TreeOptions {
  /** Force the WAL to sync before acknowledging each write. */
  walSync?: boolean
}
