/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A Node.js handle to a Holt multi-tree database. */
export declare class Database {
  /**
   * Open a file-backed multi-tree database without blocking the Node.js
   * event loop.
   */
  static open(path: string, options?: TreeOptions | undefined | null): Promise<Database>
  /**
   * Open a volatile in-memory multi-tree database without blocking the
   * Node.js event loop.
   */
  static openMemory(): Promise<Database>
  /**
   * Explicitly release the database handle on a worker thread. Existing
   * Tree handles remain usable until they are closed or dropped.
   */
  close(): Promise<void>
  /** Create a new named tree on a worker thread. */
  createTree(name: string): Promise<Tree>
  /** Open an existing named tree on a worker thread. */
  openTree(name: string): Promise<Tree>
  /** Open a named tree on a worker thread, creating it when absent. */
  openOrCreateTree(name: string): Promise<Tree>
  /** List all live named trees on a worker thread. */
  listTrees(): Promise<Array<string>>
  /** Drop a named tree and fence existing handles on a worker thread. */
  dropTree(name: string): Promise<void>
  /** Flush every named tree and the shared WAL on a worker thread. */
  checkpoint(): Promise<void>
}

/** A Node.js handle to one Holt tree. */
export declare class Tree {
  /** Open a file-backed tree without blocking the Node.js event loop. */
  static open(path: string, options?: TreeOptions | undefined | null): Promise<Tree>
  /** Open a volatile in-memory tree without blocking the Node.js event loop. */
  static openMemory(): Promise<Tree>
  /** Explicitly release the native tree handle on a worker thread. */
  close(): Promise<void>
  /** Return the value at `key` from a worker thread. */
  get(key: Uint8Array): Promise<Buffer | null>
  /** Return the value and conditional-write version from a worker thread. */
  getRecord(key: Uint8Array): Promise<Record | null>
  /** Insert or replace a value on a worker thread. */
  put(key: Uint8Array, value: Uint8Array): Promise<void>
  /** Delete a key on a worker thread and return whether it existed. */
  delete(key: Uint8Array): Promise<boolean>
  /** Compare the current version and replace the value on a worker thread. */
  compareAndPut(key: Uint8Array, version: bigint, value: Uint8Array): Promise<boolean>
  /** Flush dirty frames and the WAL on a worker thread. */
  checkpoint(): Promise<void>
  /** Scan keys on a worker thread. */
  scanKeys(prefix?: Uint8Array | undefined | null, options?: ScanOptions | undefined | null): Promise<Array<ScanEntry>>
  /** Scan records on a worker thread. */
  scanRecords(prefix?: Uint8Array | undefined | null, options?: ScanOptions | undefined | null): Promise<Array<ScanEntry>>
}

/** A live value and its conditional-write version. */
export interface Record {
  /** Value bytes stored at the key. */
  value: Buffer
  /** Version token for compare-and-put. */
  version: bigint
}

/** One emitted scan entry. */
export interface ScanEntry {
  /** `key` for a live record or `common_prefix` for a rollup. */
  kind: string
  /** Key or common-prefix bytes. */
  path: Buffer
  /** Value bytes; absent for key-only scans and common-prefix entries. */
  value?: Buffer
  /** Conditional-write version. Zero for common-prefix entries. */
  version: bigint
}

/** Options shared by key and record scans. */
export interface ScanOptions {
  /** Exclusive lower-bound key. */
  startAfter?: Uint8Array
  /** Optional delimiter byte used for common-prefix rollups. */
  delimiter?: number
}

/** Options for opening a file-backed tree or database. */
export interface TreeOptions {
  /** Force the WAL to sync before acknowledging each write. */
  walSync?: boolean
}
